package bgtasks

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/lfrystak/rptgen"
)

const (
	logoURL    = "https://assets-us-01.kc-usercontent.com/cca93d54-f979-003f-a463-4d96b4a8e385/353a7bd8-6c45-46a2-9960-48400edad9dc/Sonar%20%282%29.svg?w=128&h=32&dpr=1&fit=crop&q=80"
	footerText = "Report generated by Sonar Insights CLI"
	dateLayout = "2006-01-02"
	divClose   = "</div>"

	introParagraphHTML = `
<p>
This report presents an analysis of background tasks processed by the SonarQube Server Compute Engine over a specified period.
The input data from this report is taken from the output of the <code>GET api/ce/activity</code> REST API endpoint.
SonarQube Server keeps this information for up to 180 days.
</p>
<p>
The SonarQube Server Compute Engine is responsible for executing various background tasks,
including project analyses, portfolio recalculations, and project reindexing.
<strong>The Compute Engine is the most critical component when evaluating SonarQube Server's performance</strong>,
as it directly impacts analysis throughput, which in turn affects the speed of CI/CD pipelines
and how quickly developers receive SonarQube feedback in their DevOps platforms.
Starting from the Enterprise Edition, SonarQube Server supports multiple Compute Engine workers,
enabling parallel processing of background tasks to significantly improve performance and scalability.
</p>
<p>
<strong>The goal of this report</strong> is to provide insights into your SonarQube Server's
Compute Engine workload patterns and suggest recommendations for capacity planning and performance optimization.
By analyzing historical task data, this report aims to help you evaluate the appropriate number of Compute Engine workers
to support your organization's performance requirements and service level objectives.
</p>
<p>
<strong>Note on Timestamps:</strong> All date and time values in this report are analyzed and presented in Coordinated Universal Time (UTC).
Task submission times, execution windows, and capacity demand calculations are all based on UTC timestamps,
ensuring consistent analysis regardless of the SonarQube Server's local timezone configuration or the timezone where this analysis is run.
</p>
`

	overallSectionHTML = `
<p>
<strong>The first section provides a high-level summary of the analyzed background tasks data.</strong>
All task types are included in this section (analysis reports,
portfolio recalculation, project reindexing, etc.).
</p>
`

	projectSectionHTML = `
<p>
This section focuses specifically on <strong>background tasks related to project analyses</strong> (task type 'REPORT').
It provides insights into the volume and distribution of project analysis tasks over the analyzed period.
Project analyses are the largest consumer of compute resources on the SonarQube Compute Engine, so
understanding their patterns is crucial for performance evaluation, capacity planning, and optimization.
</p>
`
)

// BuildReport assembles an rptgen Report from analysis results.
func BuildReport(results AnalysisResults) *rptgen.Report {
	report := rptgen.NewReport("SonarQube Server Compute Engine Analysis")
	report.LogoURL = logoURL
	report.Footer = footerText

	report.AddSection(buildIntroSection())
	report.AddSection(buildOverallSection(results))
	report.AddSection(buildProjectSection(results))
	report.AddSection(buildCapacitySection(results.CapacityDemand))

	return report
}

// RenderToFile renders the report to an HTML file at path.
func RenderToFile(report *rptgen.Report, path string) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create report file: %w", err)
	}
	defer func() { _ = f.Close() }()
	return renderTo(report, f)
}

func renderTo(report *rptgen.Report, w io.Writer) error {
	return rptgen.HtmlRenderer{}.Render(w, report, nil)
}

func buildIntroSection() *rptgen.Section {
	s := rptgen.NewSection("Introduction")
	s.AddElement(&rptgen.FreeText{Content: introParagraphHTML, IsHTML: true})
	return s
}

func buildOverallSection(results AnalysisResults) *rptgen.Section {
	s := rptgen.NewSection("Overall background tasks summary")
	s.AddElement(&rptgen.FreeText{Content: overallSectionHTML, IsHTML: true})

	canvas := rptgen.NewCanvas(rptgen.EqualColumns(3)...)
	canvas.AddElement(dateTile("Start of analyzed period",
		results.DateRange.EarliestSubmission,
		"The UTC date when the first task was submitted in the analyzed period/data"))
	canvas.AddElement(dateTile("End of analyzed period",
		results.DateRange.LatestCompletion,
		"The UTC date when the last task was completed in the analyzed period/data"))
	canvas.AddElement(intTile("Total days analyzed",
		results.DateRange.DateRangeInDays,
		"The total number of days covered by the analyzed data"))
	canvas.AddElement(intTile("Total tasks analyzed",
		results.Overall.TotalUniqueTasks,
		"The total number of background tasks processed in the analyzed period/data"))
	canvas.AddElement(floatTile("Average tasks per day", results.Overall.AverageTasksPerDay, "%.1f"))
	canvas.AddElement(intTile("Max tasks in a day",
		results.Overall.BusiestDayTaskCount,
		"The highest number of tasks submitted on a single day in the analyzed period/data"))
	s.AddElement(canvas)

	s.AddElement(buildStackedBarByType(results.Charts))

	pieCanvas := rptgen.NewCanvas(rptgen.EqualColumns(2)...)
	pieCanvas.AddElement(buildPieChart("Tasks by Type", results.Charts.SummaryByType))
	failedLabel := fmt.Sprintf("%.2f%%", results.Overall.FailedTasksPercentage)
	statusPie := buildPieChart("Tasks by Status", results.Charts.SummaryByStatus)
	statusPie.Tooltip = fmt.Sprintf("Distribution of tasks by their final status. Failed tasks account for %s of all tasks.", failedLabel)
	statusPie.IsDonut = true
	pieCanvas.AddElement(statusPie)
	s.AddElement(pieCanvas)

	return s
}

func buildProjectSection(results AnalysisResults) *rptgen.Section {
	s := rptgen.NewSection("Summary of project analysis background tasks only")
	s.AddElement(&rptgen.FreeText{Content: projectSectionHTML, IsHTML: true})

	canvas := rptgen.NewCanvas(rptgen.EqualColumns(3)...)
	canvas.AddElement(intTile("Total project analyzed",
		results.ProjectAnalysis.TotalProjectsAnalyzed,
		"The total number of unique projects analyzed in the analyzed period/data"))
	canvas.AddElement(intTile("Total project analysis tasks",
		results.ProjectAnalysis.TotalProjectAnalysisTasks,
		"The total number of project analysis tasks processed in the analyzed period/data"))
	canvas.AddElement(floatTile("Average project analysis tasks per day",
		results.ProjectAnalysis.AverageProjectAnalysisTasks, "%.1f"))
	s.AddElement(canvas)

	s.AddElement(buildBarChartFromDayMap("Project analyses per day", results.Charts.ProjectAnalysesPerDay))

	inner := rptgen.NewCanvas(rptgen.EqualColumns(2)...)
	inner.AddElement(buildBarChartFromTimePct("Summary by pending time (%)", results.Charts.SummaryByPendingTime))
	inner.AddElement(buildBarChartFromTimePct("Summary by execution time (%)", results.Charts.SummaryByExecutionTime))
	inner.AddElement(buildPieChart("Branch vs PR analyses", map[string]int{
		"Branch Analyses":       results.ProjectAnalysis.TotalBranchAnalysisTasks,
		"Pull Request Analyses": results.ProjectAnalysis.TotalPullRequestAnalysisTasks,
	}))
	inner.AddElement(buildBarChartFromFloatMap("Branch and PR analysis execution time comparison",
		results.ProjectAnalysis.BranchAndPrExecutionTimesSec))
	s.AddElement(inner)

	s.AddElement(buildTopProjectsTable(results.ProjectAnalysis.TopProjects))

	for i, series := range results.Charts.TopProjectBranchExecTimes {
		title := fmt.Sprintf("Branch Execution Times For %s Most Analyzed Project (execution time in seconds)",
			ordinal(i+1))
		s.AddElement(buildLineChart(title, series))
	}

	return s
}

func buildCapacitySection(cap CapacityDemandResults) *rptgen.Section {
	s := rptgen.NewSection("Capacity Demand Analysis")
	s.AddElement(&rptgen.FreeText{Content: buildCapacityHTML(cap), IsHTML: true})
	return s
}

// --- element helpers ---

func dateTile(title string, t time.Time, subtitle string) *rptgen.DateTile {
	tile := rptgen.NewDateTile(title, t.UTC())
	tile.Format = dateLayout
	tile.Subtitle = subtitle
	return tile
}

func intTile(title string, val int, subtitle string) *rptgen.NumberTile {
	tile := rptgen.NewNumberTile(title, float64(val))
	tile.Format = "%.0f"
	tile.ThousandsSep = true
	tile.Subtitle = subtitle
	return tile
}

func floatTile(title string, val float64, format string) *rptgen.NumberTile {
	tile := rptgen.NewNumberTile(title, val)
	tile.Format = format
	return tile
}

func buildPieChart(title string, m map[string]int) *rptgen.PieChart {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	pts := make([]rptgen.DataPoint, len(keys))
	for i, k := range keys {
		pts[i] = rptgen.DataPoint{Label: k, Value: float64(m[k])}
	}
	c := rptgen.NewPieChart(title, pts)
	c.IsDonut = true
	return c
}

func buildStackedBarByType(charts ChartDatasets) *rptgen.StackedBarChart {
	days := sortedDays(charts.TasksPerDayByType)
	series := make([]rptgen.StackedBarSeries, len(days))
	for i, d := range days {
		vals := make(map[string]float64, len(charts.AllTaskTypes))
		for _, tp := range charts.AllTaskTypes {
			vals[tp] = float64(charts.TasksPerDayByType[d][tp])
		}
		series[i] = rptgen.StackedBarSeries{Category: d.Format(dateLayout), Values: vals}
	}
	c := rptgen.NewStackedBarChart("Background tasks per day incl. task type", series)
	c.Tooltip = "Number of tasks per day broken down by task type. Click on legend items to show/hide specific task types."
	return c
}

func buildBarChartFromDayMap(title string, m map[time.Time]int) *rptgen.BarChart {
	days := sortedDaysInt(m)
	pts := make([]rptgen.DataPoint, len(days))
	for i, d := range days {
		pts[i] = rptgen.DataPoint{Label: d.Format(dateLayout), Value: float64(m[d])}
	}
	c := rptgen.NewBarChart(title, pts)
	c.UniformColor = true
	return c
}

func buildBarChartFromTimePct(title string, metrics []TimeCategoryMetric) *rptgen.BarChart {
	pts := make([]rptgen.DataPoint, len(metrics))
	for i, m := range metrics {
		pts[i] = rptgen.DataPoint{Label: m.Label, Value: m.Percentage}
	}
	c := rptgen.NewBarChart(title, pts)
	c.UniformColor = true
	return c
}

func buildBarChartFromFloatMap(title string, m map[string]float64) *rptgen.BarChart {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	pts := make([]rptgen.DataPoint, len(keys))
	for i, k := range keys {
		pts[i] = rptgen.DataPoint{Label: k, Value: m[k]}
	}
	c := rptgen.NewBarChart(title, pts)
	c.UniformColor = true
	return c
}

func buildTopProjectsTable(projects []TopProject) *rptgen.Table {
	rows := make([]map[string]any, len(projects))
	for i, p := range projects {
		rows[i] = map[string]any{
			"Project":    p.Key,
			"Count":      p.Count,
			"Percentage": fmt.Sprintf("%.2f%%", p.Percentage),
		}
	}
	return rptgen.NewTableWithColumns("Top 10 most analyzed projects", rows, []string{"Project", "Count", "Percentage"})
}

func buildLineChart(title string, series BranchExecutionTimeSeries) *rptgen.LineChart {
	pts := make([]rptgen.DataPoint, len(series.ExecutionTimesSeconds))
	for i, p := range series.ExecutionTimesSeconds {
		pts[i] = rptgen.DataPoint{Label: p.Label, Value: p.Seconds}
	}
	return rptgen.NewLineChartSingle(title, pts)
}

func sortedDays(m map[time.Time]map[string]int) []time.Time {
	days := make([]time.Time, 0, len(m))
	for d := range m {
		days = append(days, d)
	}
	sort.Slice(days, func(i, j int) bool { return days[i].Before(days[j]) })
	return days
}

func sortedDaysInt(m map[time.Time]int) []time.Time {
	days := make([]time.Time, 0, len(m))
	for d := range m {
		days = append(days, d)
	}
	sort.Slice(days, func(i, j int) bool { return days[i].Before(days[j]) })
	return days
}

func ordinal(n int) string {
	switch n {
	case 1:
		return "First"
	case 2:
		return "Second"
	case 3:
		return "Third"
	default:
		return fmt.Sprintf("%dth", n)
	}
}

// --- capacity demand HTML (mirrors ReportDataPreparer.BuildCapacityDemandHtml) ---

const recommendationPercentile = 0.99

func buildCapacityHTML(cap CapacityDemandResults) string {
	if len(cap.PercentileAnalyses) == 0 {
		return "<p>No capacity demand analysis data available.</p>"
	}
	rec := computeRecommendation(cap)

	var sb strings.Builder
	sb.WriteString("<div style='font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; padding: 0px 25px; margin: 5px 0;'>")
	sb.WriteString("<h4 style='color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px;'>📊 Capacity Demand Analysis Summary</h4>")
	sb.WriteString("<div style='margin: 15px; text-align: justify;'>")
	writeRecommendationHTML(&sb, rec)
	sb.WriteString(divClose)
	writeCollapsible(&sb, "🔍 Detailed Capacity Demand Analysis", func() { writeDetailedHTML(&sb, cap) })
	writeCollapsible(&sb, "ℹ️ About the Capacity Demand Calculation Methodology", writeMethodologyHTML(&sb))
	sb.WriteString(divClose)
	return sb.String()
}

// --- recommendation ---

type capacityRecommendation struct {
	workersNeeded     int
	source            string
	bucketCount       int
	data              PercentileResult
	bucketLengthMin   int
	windowStart       time.Time
	windowEnd         time.Time
	allBucketsWorkers *int
	weekdayWorkers    *int
}

// findPercentileAnalyses locates the All-Buckets and Weekday analyses by label.
func findPercentileAnalyses(analyses []PercentileAnalysis) (*PercentileAnalysis, *PercentileAnalysis) {
	var allBuckets, weekday *PercentileAnalysis
	for i := range analyses {
		a := &analyses[i]
		if strings.Contains(a.Label, "All Buckets") {
			allBuckets = a
		} else if strings.Contains(a.Label, "Weekday") {
			weekday = a
		}
	}
	return allBuckets, weekday
}

// extractAtPercentile returns the PercentileResult and bucket count for a given percentile level.
func extractAtPercentile(a *PercentileAnalysis, p float64) (*PercentileResult, int) {
	if a == nil {
		return nil, 0
	}
	pr, ok := a.Percentiles[p]
	if !ok {
		return nil, 0
	}
	return &pr, a.BucketCount
}

func optionalWorkers(data *PercentileResult) *int {
	if data == nil {
		return nil
	}
	w := WorkersNeeded(data.SingleWorkerUtilization)
	return &w
}

func computeRecommendation(cap CapacityDemandResults) *capacityRecommendation {
	allBuckets, weekday := findPercentileAnalyses(cap.PercentileAnalyses)
	allData, allCount := extractAtPercentile(allBuckets, recommendationPercentile)
	weekData, weekCount := extractAtPercentile(weekday, recommendationPercentile)

	useWeekday := weekData != nil && (allData == nil || weekData.SingleWorkerUtilization > allData.SingleWorkerUtilization)
	var recData *PercentileResult
	var source string
	var count int
	if useWeekday {
		recData, source, count = weekData, "Weekday Buckets", weekCount
	} else {
		recData, source, count = allData, "All Buckets (24/7)", allCount
	}
	if recData == nil {
		return nil
	}

	return &capacityRecommendation{
		workersNeeded:     WorkersNeeded(recData.SingleWorkerUtilization),
		source:            source,
		bucketCount:       count,
		data:              *recData,
		bucketLengthMin:   cap.BucketLengthMinutes,
		windowStart:       cap.AnalysisWindowStart,
		windowEnd:         cap.AnalysisWindowEnd,
		allBucketsWorkers: optionalWorkers(allData),
		weekdayWorkers:    optionalWorkers(weekData),
	}
}

func writeRecommendationHTML(sb *strings.Builder, rec *capacityRecommendation) {
	if rec == nil {
		sb.WriteString("<p style='color: #757575; font-style: italic;'>Unable to generate recommendation - no percentile data available for the configured percentile.</p>")
		return
	}

	pLabel := fmt.Sprintf("%.0fth", recommendationPercentile*100)
	demandMin := rec.data.PercentileMs / 1000.0 / 60.0
	workerWord, areIs := "worker", "is"
	if rec.workersNeeded > 1 {
		workerWord, areIs = "workers", "are"
	}

	sb.WriteString("<h4 style='color: #2c3e50; margin-top: 20px;'>Recommendation</h4>")
	sb.WriteString("<div style='background-color: #e8f5e9; padding: 16px; border-left: 4px solid #4caf50; margin-bottom: 20px;'>")
	fmt.Fprintf(sb, "<p style='margin: 0; font-size: 1.05em;'><strong>Based on the %s percentile of capacity demand, <span style='color: #2e7d32;'>%d Compute Engine %s</span> %s recommended.</strong></p>",
		pLabel, rec.workersNeeded, workerWord, areIs)
	fmt.Fprintf(sb, "<p style='margin: 8px 0 0 0; color: #555;'>This configuration would handle %.0f%% of all time periods without queuing delays.</p>",
		recommendationPercentile*100)
	sb.WriteString(divClose)

	sb.WriteString("<h4 style='color: #2c3e50; margin-top: 20px;'>Summary</h4>")
	sb.WriteString("<ul style='line-height: 1.8; color: #333;'>")
	fmt.Fprintf(sb, "<li><strong>Percentile Used:</strong> %s</li>", pLabel)
	fmt.Fprintf(sb, "<li><strong>Demand at %s Percentile:</strong> %.2f min of work per %d-minute bucket</li>", pLabel, demandMin, rec.bucketLengthMin)
	fmt.Fprintf(sb, "<li><strong>Single Worker Utilization:</strong> %.1f%%</li>", rec.data.SingleWorkerUtilization)
	fmt.Fprintf(sb, "<li><strong>Data Source:</strong> %s (higher demand selected)</li>", rec.source)
	fmt.Fprintf(sb, "<li><strong>Buckets Analyzed:</strong> %d (%d-minute intervals)</li>", rec.bucketCount, rec.bucketLengthMin)
	if !rec.windowStart.IsZero() && !rec.windowEnd.IsZero() {
		fmt.Fprintf(sb, "<li><strong>Coverage Period:</strong> %.1f days</li>", rec.windowEnd.Sub(rec.windowStart).Hours()/24)
	}
	sb.WriteString("</ul>")
	writeWorkerComparisonNote(sb, rec)
}

func writeWorkerComparisonNote(sb *strings.Builder, rec *capacityRecommendation) {
	if rec.allBucketsWorkers == nil || rec.weekdayWorkers == nil {
		return
	}
	allW, wdW := *rec.allBucketsWorkers, *rec.weekdayWorkers
	if allW == wdW {
		return
	}
	sb.WriteString("<div style='background-color: #f5f5f5; padding: 12px; border-left: 3px solid #757575; margin-top: 10px; font-size: 0.95em;'>")
	fmt.Fprintf(sb, "<strong>Note:</strong> All Buckets (24/7) analysis suggests %d %s, while Weekday Buckets analysis suggests %d %s. The higher value was used for the recommendation.",
		allW, workerSuffix(allW), wdW, workerSuffix(wdW))
	sb.WriteString(divClose)
}

func workerSuffix(n int) string {
	if n == 1 {
		return "worker"
	}
	return "workers"
}

// --- detailed analysis table ---

func writeDetailedHTML(sb *strings.Builder, cap CapacityDemandResults) {
	allBuckets, weekday := findPercentileAnalyses(cap.PercentileAnalyses)
	if allBuckets == nil && weekday == nil {
		sb.WriteString("<p>No percentile analysis data available.</p>")
		return
	}
	levels := collectPercentileLevels(allBuckets, weekday)

	sb.WriteString("<h4 style='color: #2c3e50; margin-top: 25px;'>Capacity Demand Comparison</h4>")
	sb.WriteString("<table style='border-collapse: collapse; width: 100%; margin-bottom: 20px;'>")
	writeDetailedTableHeader(sb, allBuckets, weekday)
	writeDetailedTableBody(sb, levels, allBuckets, weekday)
	sb.WriteString("</table>")
	writeCapacityPlanningNotes(sb, allBuckets)
}

func collectPercentileLevels(analyses ...*PercentileAnalysis) []float64 {
	levelSet := make(map[float64]struct{})
	for _, a := range analyses {
		if a == nil {
			continue
		}
		for p := range a.Percentiles {
			levelSet[p] = struct{}{}
		}
	}
	levels := make([]float64, 0, len(levelSet))
	for p := range levelSet {
		levels = append(levels, p)
	}
	sort.Float64s(levels)
	return levels
}

func writeDetailedTableHeader(sb *strings.Builder, allBuckets, weekday *PercentileAnalysis) {
	sb.WriteString("<thead><tr style='background-color: #5a67d8; color: white;'>")
	sb.WriteString("<th style='padding: 12px; text-align: left; font-weight: 600; border-right: 1px solid #ddd;' rowspan='2'>Percentile</th>")
	if allBuckets != nil {
		sb.WriteString("<th style='padding: 12px; text-align: center; font-weight: 600; border-right: 1px solid #ddd;' colspan='3'>All Buckets (24/7)</th>")
	}
	if weekday != nil {
		sb.WriteString("<th style='padding: 12px; text-align: center; font-weight: 600;' colspan='3'>Weekday Buckets Only</th>")
	}
	sb.WriteString("</tr><tr style='background-color: #5a67d8; color: white; border-bottom: 2px solid #ddd;'>")
	if allBuckets != nil {
		writeHeaderSubCols(sb, weekday != nil)
	}
	if weekday != nil {
		writeHeaderSubCols(sb, false)
	}
	sb.WriteString("</tr></thead>")
}

func writeHeaderSubCols(sb *strings.Builder, hasBorder bool) {
	borderStyle := ""
	if hasBorder {
		borderStyle = " border-right: 1px solid #ddd;"
	}
	sb.WriteString("<th style='padding: 12px; text-align: right; font-weight: 600;'>Demand per Bucket</th>")
	sb.WriteString("<th style='padding: 12px; text-align: right; font-weight: 600;'>Workers Needed</th>")
	fmt.Fprintf(sb, "<th style='padding: 12px; text-align: right; font-weight: 600;%s'>Single Worker Utilization</th>", borderStyle)
}

func writeDetailedTableBody(sb *strings.Builder, levels []float64, allBuckets, weekday *PercentileAnalysis) {
	sb.WriteString("<tbody>")
	for _, p := range levels {
		writeDetailedTableRow(sb, p, allBuckets, weekday)
	}
	sb.WriteString("</tbody>")
}

func writeDetailedTableRow(sb *strings.Builder, p float64, allBuckets, weekday *PercentileAnalysis) {
	pLabel := fmt.Sprintf("%.1fth", p*100)
	if p == 1.0 {
		pLabel = "100th (Max)"
	}
	rowColor := "#f8f9fa"
	if maxPercentileUtil(p, allBuckets, weekday) > 100 {
		rowColor = "#fff3cd"
	}
	fmt.Fprintf(sb, "<tr style='border-bottom: 1px solid #eee; background-color: %s;'>", rowColor)
	fmt.Fprintf(sb, "<td style='padding: 10px; border-right: 1px solid #ddd;'><strong>%s</strong></td>", pLabel)
	if allBuckets != nil {
		writeAnalysisCells(sb, allBuckets, p, weekday != nil)
	}
	if weekday != nil {
		writeAnalysisCells(sb, weekday, p, false)
	}
	sb.WriteString("</tr>")
}

func maxPercentileUtil(p float64, analyses ...*PercentileAnalysis) float64 {
	max := 0.0
	for _, a := range analyses {
		if a == nil {
			continue
		}
		if pr, ok := a.Percentiles[p]; ok && pr.SingleWorkerUtilization > max {
			max = pr.SingleWorkerUtilization
		}
	}
	return max
}

func writeAnalysisCells(sb *strings.Builder, a *PercentileAnalysis, p float64, hasBorder bool) {
	borderStyle := ""
	if hasBorder {
		borderStyle = " border-right: 1px solid #ddd;"
	}
	if pr, ok := a.Percentiles[p]; ok {
		fmt.Fprintf(sb, "<td style='padding: 10px; text-align: right;'>%.2f min</td>", pr.PercentileMs/1000.0/60.0)
		fmt.Fprintf(sb, "<td style='padding: 10px; text-align: right;'>%d</td>", WorkersNeeded(pr.SingleWorkerUtilization))
		fmt.Fprintf(sb, "<td style='padding: 10px; text-align: right;%s'>%.2f%%</td>", borderStyle, pr.SingleWorkerUtilization)
	} else {
		fmt.Fprintf(sb, "<td style='padding: 10px; text-align: right;'>-</td>")
		fmt.Fprintf(sb, "<td style='padding: 10px; text-align: right;'>-</td>")
		fmt.Fprintf(sb, "<td style='padding: 10px; text-align: right;%s'>-</td>", borderStyle)
	}
}

func writeCapacityPlanningNotes(sb *strings.Builder, allBuckets *PercentileAnalysis) {
	sb.WriteString("<h4 style='color: #2c3e50; margin-top: 25px;'>Capacity Planning Recommendations</h4>")
	if allBuckets != nil {
		sb.WriteString("<p style='line-height: 1.6; color: #333; margin-bottom: 15px;'>")
		sb.WriteString("The higher the percentile chosen, the more resilient your server will be to short periods of high demand. ")
		sb.WriteString("Lower percentiles (e.g., 90%) provide conservative provisioning suitable for typical workloads with occasional queuing during peaks, ")
		sb.WriteString("while higher percentiles (e.g., 99.9%) ensure very generous provisioning that can handle nearly all demand spikes without delays.")
		sb.WriteString("</p>")
	} else {
		sb.WriteString("<p style='color: #757575; font-style: italic;'>Unable to generate specific recommendations without percentile analysis data.</p>")
	}
}

func writeCollapsible(sb *strings.Builder, title string, fn func()) {
	sb.WriteString("<details style='margin-top: 10px;'>")
	fmt.Fprintf(sb, "<summary style='font-size: 1.1em; font-weight: 600; cursor: pointer; color: #2980b9;'>%s (click to expand)</summary>", title)
	sb.WriteString("<div style='margin: 15px; text-align: justify;'>")
	fn()
	sb.WriteString(divClose + "</details>")
}

func writeMethodologyHTML(sb *strings.Builder) func() {
	return func() {
		sb.WriteString(`<h4>What is Calculated and How</h4>
<p>This section of the report estimates Compute Engine capacity demand by dividing the analysis
timeline into fixed-length time buckets (aligned to UTC) and calculating the theoretical demand within each bucket.
For each background task, the algorithm assumes execution could have started immediately upon
submission and distributes its execution time across all buckets that overlap with this theoretical
execution window. When a task's execution window spans multiple buckets, the execution time is
proportionally allocated based on how much of the window falls within each bucket. The result is a
demand value per bucket (measured as accumulated execution time), which is then used to calculate
percentiles across all buckets to identify typical and peak capacity requirements.</p>
<h4>Why This Approach is Used</h4>
<p>The available input data includes submission time, actual execution start time, and actual
execution end time for each task, but these timestamps have only 1-second resolution. This
limited resolution makes it impossible to accurately reconstruct the historical state of the
task queue at any given moment—specifically, which tasks were running in parallel versus which
were queued waiting for available workers. By calculating demand from the submission timestamp
instead (assuming tasks could execute immediately), the algorithm produces a theoretical upper
bound on capacity requirements that is independent of the historical worker configuration.</p>
<h4>Performance Considerations Beyond Worker Count</h4>
<p>While this section of the report focuses on Compute Engine worker capacity, it is critical to
understand that SonarQube Server performance and analysis throughput depend on multiple interrelated
factors. An important caveat when interpreting these results: if the SonarQube Server was already
experiencing performance problems during the analyzed period (such as database saturation, CPU
exhaustion, or memory pressure), the calculated demand values will reflect this degraded state.
The database is often the single biggest performance bottleneck in production deployments.
Effective capacity planning requires holistic evaluation of all infrastructure components,
proper database tuning, and incremental worker scaling with performance validation at each step.</p>`)
	}
}
