version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-
    🙏 Thank you for using {{ .ProjectName }}!

    ❓ Any questions or issues? Please open an issue at {{ .GitURL }}/issues.

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
